version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud_root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud_network

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - nextcloud_network

  nextcloud:
    image: nextcloud:28-apache
    container_name: nextcloud-app
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - nextcloud_data:/var/www/html
      - ./nextcloud-app/outlook_integrator:/var/www/html/custom_apps/outlook_integrator
      - ./certs:/certs:ro
      - ./apache-ssl.conf:/etc/apache2/sites-available/default-ssl.conf:ro
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin123
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost nextcloud.local 127.0.0.1
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.local
      - OVERWRITECLIURL=https://nextcloud.local
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network

volumes:
  db_data:
    driver: local
  nextcloud_data:
    driver: local

networks:
  nextcloud_network:
    driver: bridge

